### ISSUE TITLE
Change colour of chosen talks under Events Tab

### ISSUE THREAD

**Issue by phillips321** [BeezleLabs/HackerTracker-iOS#1]
In order to make it easier to know which events I've already selected can we change the colour to green for events I have selected? It would also be good to change the colour to red of events(talks) that now clash...?

**Comment by sethlaw** [comment]
Good suggestion, I'm picking this up and will push to the App Store, not sure if it will make it before the con this year.

**Comment by sethlaw** [comment]
Fixed in DC 24 version. Selected talks now show up highlighted with the years color and stars.
