### ISSUE TITLE
DC26 - New Content - DEF CON Parties

### ISSUE THREAD

**Issue by zevlag** [BeezleLabs/HackerTracker-iOS#105]
Yeah, this is way away from official, but it would be nice to have DEF CON Parties on Hacker Tracker.

http://defconparties.com/

**Comment by Advice-Dog** [comment]
Hey @zevlag, I believe we do already have most of those parties. If you see anything specific we're missing let us know.

**Comment by zevlag** [comment]
Sweet! I do see them now.  That content wasn't showing when I started making this ticket yesterday.
