### ISSUE TITLE
iOS Notifications contain “Optional” Text

### ISSUE THREAD

**Issue by aNullValue** [BeezleLabs/HackerTracker-iOS#122]
Notifications are printing extraneous “Optional()” text. 

![79A6B0E5-8202-4988-B43A-A650DFCA91A6](https://user-images.githubusercontent.com/3424516/57157974-ca268980-6da7-11e9-9b56-4a2d067317eb.png)

**Comment by zactly-seth** [comment]
Fixed in most recent push for defcon27

**Comment by sethlaw** [comment]
confirmed fixed
