### ISSUE TITLE
DC27 - New Content - Packet Hacking Village

### ISSUE THREAD

**Issue by zevlag** [BeezleLabs/HackerTracker-iOS#126]
Villages are starting to post content, just contributing them here to help organize.

If there is a better/preferred method for me to contribute, please let me know. ie. providing JSON, posting in a slack somewhere, etc...

https://www.reddit.com/r/Defcon/comments/c5wzjf/packet_hacking_village_talks_at_def_con_27/

https://www.wallofsheep.com/blogs/news/packet-hacking-village-talks-and-schedule-at-def-con-27-finalized

**Comment by sethlaw** [comment]
added for defcon 27.
