### ISSUE TITLE
Feature request: Optional localization of time

### ISSUE THREAD

**Issue by aNullValue** [BeezleLabs/HackerTracker-iOS#133]
DEF CON and other conferences are now holding events virtually, which means that attendees no longer have a timezone in common.

HT4Android makes localization optional:
Menu -> Settings -> Events in local timezone (<name of conference default timezone>): toggle
Off: Times are expressed local to the device's current timezone
On: Times are expressed local to the conference's default timezone

Timezone knowledge/discoverability will also need to be taken into consideration. Perhaps the currently effective timezone could be printed near times on views where that's feasible (such as the "event detail" view)? I would be fine with UTC offset (i.e., "UTC-07:00"), but I (baselessly) suspect that most humans would be more comfortable with tz name (i.e., "America/Los_Angeles"). 

I believe that this request should be considered critical. DEF CON 28's official & default timezone is Etc/UTC. While many of us would not have difficulty localizing the time mentally, I'm sure that there are many, many others who will have great difficulty with that. 

(FWIW, in case it's considered, I'm not a fan of the idea of simply always localizing times. When conferences are held in-person, it's useful to be able to view the schedule using the conference-local times, even if you haven't yet arrived in that timezone.)

**Comment by sethlaw** [comment]
This is fixed, will be pushed to App Store within the next couple days.

**Comment by sethlaw** [comment]
Completed and pushed.
