### ISSUE TITLE
DC25: Add flagged icon to event cell for starred events

### ISSUE THREAD

**Issue by sethlaw** [BeezleLabs/HackerTracker-iOS#19]

**Comment by chrsmys** [comment]
@sethlaw Can you give a little more detail on this one?

**Comment by sethlaw** [comment]
Just want to visually show which events were selected using the flagged icon instead of just color changes. Meghan's original design used different colors on the table events that weren't related to something that was favorited, etc.

**Comment by sethlaw** [comment]
Might just close this, the purple bar seems to work fine, unless there is other thoughts on this and we want the other colors on the table views.

**Comment by chrsmys** [comment]
Spoke with @megmacera, the bar is meant to indicate that it is a starred event. We need to determine colors based on event type. Closing this issue and adding a new one.
