### ISSUE TITLE
Application crashes when trying to sync

### ISSUE THREAD

**Issue by jeffmaxton** [BeezleLabs/HackerTracker-iOS#3]
Every time I try to sync, the application crashes and exits.

**Comment by sethlaw** [comment]
Can you tell me what iOS device and version you are using? Some others have seen this and I'm trying to track down the issue. Remember that info.defcon.org is not available until 8/5 and you won't be able to sync with the service until then.

**Comment by jeffmaxton** [comment]
It fails on an iPhone 6.  Gets to the 'Connection Request' dialog and as
soon as i hit yes, it crashes.
I tried it on my iPad Mini and it doesn't crash...just says can't reach the
info.defcon.org address.

Thanks,
Jeff

**Comment by qayshp** [comment]
Same crash on iPhone 5s using iOS 8.4, and a review on the App Store mentions the crash on 8.1 with an iPod.
