### ISSUE TITLE
Feature Proposals

### ISSUE THREAD

**Issue by chrsmys** [BeezleLabs/HackerTracker-iOS#8]
Hello,

I have a couple of Ideas for the app that I wish to implement, but I would like to get some feedback before doing so:
- [ ]  Local Notifications support 
  - I would like to add  local notifications that fire when an 'added' talk is about to start.
- [ ]  UI Cleanup
  - I think it would be nice to clean up the UI a bit in order to better match Apple's [HIG](https://developer.apple.com/ios/human-interface-guidelines/)
  - Change some buttons to use images instead of text (Close = X Icon, Add = Star Icon)
  - There are several locations in the app that have vertical scrolling scrollviews within vertical scrollviews. I feel this user experience could be improved by allowing everything in the vertical scrollview to scroll as one unit.
- [ ] App Extensions
  - A today widget that shows upcoming talks would be a neat feature and not very difficult to implement.
  - On that same note a watch app that does the same would also be an interesting route to go.
  
  Thanks,
  -Chris

**Comment by sethlaw** [comment]
Chris:

Awesome feedback, all sounds reasonable and I’ll add these as feature requests/issues. Some of them are along the lines of things I noticed using it this year as well. Thanks for taking the time to send these over.

—Seth

**Comment by biscuitehh** [comment]
I can start working on the watch app @chrsmys unless it's already being worked on by somebody else.

**Comment by sethlaw** [comment]
That would be great, I just made sure that github is current with version 1.2.9 in the App Store. Please clone/create a branch to start the watch portion.

—Seth

**Comment by sethlaw** [comment]
Alongside any feature updates, we will be working more closely with the DEF CON Information booth this year. I'm going to do a big development push starting in March/April with look and feel updates, interactions with the new backend, etc.

**Comment by biscuitehh** [comment]
Sounds awesome @sethlaw - I believe @chrsmys just did a Swift 3 conversion on his fork of the repo if you wanted to take a look at it/merge it in. I'll admit I've been pretty busy the last few months but I can definitely put aside a few hours a week to get the party started.

**Comment by chrsmys** [comment]
@sethlaw I just spoke with a user experience designer at WillowTree and she is interested in helping us out with updating the look of the app. Github won't let me tag her for some reason, but she'll comment below here in a bit.

**Comment by megmacera** [comment]
Hi! Thanks @chrsmys. I would love to help out with visual design of the app if you see fit, @sethlaw.

**Comment by sethlaw** [comment]
Hi @megmacera, I would love to have your expertise. It's pretty raw currently and needs some help. Even if you just give me a baseline and/or wireframes to work from. We do want some consistency with the Android version of the application, but still want to follow Apple's UI design guidelines where it's applicable.

**Comment by megmacera** [comment]
![1](https://cloud.githubusercontent.com/assets/23507252/22656490/865085c2-ec61-11e6-8e52-3745d0bb3a0c.png)
![2](https://cloud.githubusercontent.com/assets/23507252/22656489/86452d58-ec61-11e6-900c-e7ab934ecaed.png)
![3](https://cloud.githubusercontent.com/assets/23507252/22656488/86447142-ec61-11e6-8d1a-8e685cb384dd.png)

**Comment by sethlaw** [comment]
Wow, looks awesome, I'm going to invite both of you to a dropbox folder where we can share assets, etc. Need stuff broken out into icons, images, etc, in different sizes to facilitate the changes.

**Comment by nVisium-seth-law** [comment]
@megmacera Any chance you can save out these as different assets? I'm going to push out an update in the next couple of weeks that brands the app for DC 25. Looking over your mockups, I need the launch image, background images, the icons, and specific fonts used.

Thanks!

**Comment by megmacera** [comment]
@nVisium-seth-law I can save these out as assets for you. What file type do you prefer? You mentioned a Dropbox folder...does that exist yet?

**Comment by sethlaw** [comment]
@megmacera Can you follow me on twitter or send me an email (seth.w.law [at] gmail.com) so I can add you to the dropbox folder?

**Comment by chrsmys** [comment]
I've started work on the new designs. What are the next steps as far as the api is concerned? Will there be breaking changes with DEF CON 25 coming up or is the information returned just going to get updated?

**Comment by sethlaw** [comment]
Hey Chris. I started a branch for dc25 and already have some of the designs worked out. Let me push and we can compare and contrast. 

Seth Law | seth.w.law@gmail.com

**Comment by chrsmys** [comment]
Sounds great 👍

**Comment by sethlaw** [comment]
I'm on the defcon info booth discussion on the API, which is going to have some changes this year, but let's get the initial design worked pout and then I can share the changes once they are stable. 

Seth Law | seth.w.law@gmail.com

**Comment by chrsmys** [comment]
Can I get access to Dropbox as well? It appears the fonts are not pushed up to the repo. Email is on my profile.

**Comment by sethlaw** [comment]
Just sent you an invite. Not sure why the font didn't get added, but I will look into it.

**Comment by sethlaw** [comment]
Gonna close this one out, contact me on slack if there is anything else outstanding.
